package ir.khalili.products.nas.core.enums;

public enum ConfigEnum {
    NAS_COUNT_DAILY_INQUIRY,
    NAS_COUNT_MONTHLY_INQUIRY,
    NAS_COUNT_FREE_INQUIRY,
    NAS_TIME_EXPIRE_REQUEST,
    NAS_COUNT_INQUIRY_DAILY_CIVIL_REGISTRY,
    NAS_TEXT_VIDEO_UPLOAD,
    NAS_COUNT_INQUIRY_DAILY_POST,
    NAS_NON_ATTENDANCE_AUTHENTICATION_FEE,
    NAS_RESET_USER_PASSWORD_SMS_TEXT,

    INTERNET_BANK_ACTIVE_SMS_TEXT,
    INTERNET_BANK_ACTIVE_FEE,

    MOBILE_BANK_ACTIVE_SMS_TEXT,
    MOBILE_BANK_ACTIVE_FEE,

    CHANGE_CONTACT_DETAILS_FEE,
    LOAN_FEE,
    
    
    
    LOAN_COUNT_INQUIRY_DAILY_POST
}
